### ISSUE TITLE
Unable to refer to env variables in args

### ISSUE THREAD

**Issue by jaydenseric** [entropitor/dotenv-cli#10]
This does not work when running `npm start`:

```json
"scripts": {
    "start": "dotenv next -- start -p $PORT"
}
```

The exiting error being:

```
TypeError [ERR_INVALID_OPT_VALUE]: The value "{ port: true }" is invalid for option "options"
    at Server.listen (net.js:1450:9)
    …
```

But this does work:

```json
"scripts": {
    "start": "dotenv npm run start:next",
    "start:next": "next start -p $PORT"
}
```

Unfortunately the Next.js CLI does not respect a `PORT` env variable, only the CLI `-p` arg.

**Comment by entropitor** [comment]
@jaydenseric This seems very logical to me, this is because $PORT is a shell variable so it value is expanded before the `dotenv` comand is run. This is just due to how shell scripting works AFAIK, so I'm gonna close this, especially given that it seems you've found a solution
