### ISSUE TITLE
Documentation should recommend use of "--" separator

### ISSUE THREAD

**Issue by bcheidemann** [entropitor/dotenv-cli#100]
I recently came across this package and it's excellent for my use case. However, because the documentation recommends:

```sh
dotenv -e .env2 <command with arguments>
```

I assumed I could simply run:

```sh
dotenv -e ../../../.env -- docker compose up -d
```

You can imagine my confusion to find that the "-d" flag was being ignored. I very nearly moved onto another package due to this issue.

To avoid similar foot guns, I would suggest updating the documentation to recommend:

```sh
dotenv -- <command with arguments>
dotenv -e .env2 -- <command with arguments>
```

Or to **very clearly** call out the foot guns when omitting "--" separator.

**Comment by entropitor** [comment]
I think it makes sense to change it indeed! I'd love a PR for this!
