### ISSUE TITLE
[Bug]Runtime error when using "-p" option

### ISSUE THREAD

**Issue by sa2taka** [entropitor/dotenv-cli#106]
# Info

dotenv-cli: 7.4.0 

# Steps to reproduce

Execute below command:

```
$  ENV_VALUE=dummy npx --package dotenv-cli dotenv -p ENV_VALUE
```

# Behavior

```
# ENV_VALUE=dummy npx --package dotenv-cli dotenv -p ENV_VALUE
/Users/satsuta/.npm/_npx/075ae4738b5e8eb2/node_modules/dotenv-cli/cli.js:94
    value = `\`${value}\``
          ^

TypeError: Assignment to constant variable.
    at Object.<anonymous> (/Users/sa2taka/.npm/_npx/075ae4738b5e8eb2/node_modules/dotenv-cli/cli.js:94:11)
```

# Reason

Following code seems to be attempting to overwrite the value defined by const, which seems to be causing an error.
ref: #105 

```typescript
const value = process.env[argv.p]
if (typeof value === 'string') {
  value = `\`${value}\``
}
```

Thanks.

**Comment by leethree** [comment]
I'm also seeing this since 7.4.0

**Comment by Swivelgames** [comment]
Weird! That must have been the linter. I believe I had that as a `let` before o.o

I haven't checked to see if a PR was pushed up to fix it yet, but if not, I'll push up and additional PR to fix asap.

**Comment by entropitor** [comment]
https://github.com/entropitor/dotenv-cli/releases/tag/v7.4.1
