### ISSUE TITLE
Package does not stream output of Lerna

### ISSUE THREAD

**Issue by kirill-konshin** [entropitor/dotenv-cli#11]
When Lerna is launched like so

```bash
$ dotenv lerna run start --parallel

> xxx@1.0.0 start /Users/dis/Sites/xxx
> dotenv lerna run start --parallel

lerna notice cli v3.8.4
lerna info Executing command in 2 packages: "npm run start"
```

And the no output although all scripts are running normally.

When `dotenv-cli` is added to each package and used there it works fine.

**Comment by kirill-konshin** [comment]
I have seen similar issues, it might be related to TTY: https://github.com/rollup/rollup/issues/1919

**Comment by entropitor** [comment]
Can you try this from the readme:
>If you want to pass parameters to the command use --. E.g. `mvn exec:java -Dexec.args="-g -f"` would become `dotenv mvn exec:java -- -Dexec.args="-g -f"` (See https://github.com/entropitor/dotenv-cli/issues/8)

Does it work then?

**Comment by entropitor** [comment]
Okay! Thank you very much for the immediate fix! ❤️
