### ISSUE TITLE
[Documentation] Clarify if the files specified by `-e` are read in addition to, or instead of the default ones

### ISSUE THREAD

**Issue by rulatir** [entropitor/dotenv-cli#110]
As per the title, [this passus in the README](https://github.com/entropitor/dotenv-cli?tab=readme-ov-file#custom-env-files) is unclear. I don't know if the word "another" is used in the sense of "a different one", or in the sense of "one more". Depending on the exact sense, it would mean that the file specified with `-e` will be processed instead of the default one or in addition to the default one, respectively.

**Comment by entropitor** [comment]
Updated
