### ISSUE TITLE
Breaking changes?

### ISSUE THREAD

**Issue by brortao** [entropitor/dotenv-cli#17]
Version 2.0.0 of this package was recently released, but I can't find any changelog. Usually a major version bump means backwards-incompatible changes -- what has changed?

**Comment by entropitor** [comment]
We're using dotenv-expand now, which means you can interpolate using existing or earlier defined env variables

Therefore the dollar sign would need to be escaped so in that case there is a breaking change.

Feel free to create a pr with a changelog
