### ISSUE TITLE
Outdated dotenv dependency

### ISSUE THREAD

**Issue by gavar** [entropitor/dotenv-cli#20]
dotenv should be a peer dependency to allow using latest dotenv versions

**Comment by entropitor** [comment]
The problem with this approach is that users will have to install both `dotenv-cli` and `dotenv` globally. I think we should just update the `dotenv` dependency from time to time, no? I'm open for a PR that just updates the version to the latest version

**Comment by gavar** [comment]
You're right.
I'm using it as dev dependnecy to run `semantic-release`, but I also have `dotenv` as dependency for scripts, ending up having both versions.

**Comment by entropitor** [comment]
In that case you could use https://yarnpkg.com/lang/en/docs/selective-version-resolutions/

**Comment by entropitor** [comment]
@gavar I've bumped dotenv's version in the latest release (3.0.0)
