### ISSUE TITLE
Empty string parsed as "undefined"

### ISSUE THREAD

**Issue by giuliano-sev** [entropitor/dotenv-cli#22]
```
# .env file

ENV_VARIABLE=""
```

Output
```

project_route\node_modules\dotenv-expand\lib\main.js:9
    var matches = envValue.match(/(.?\${?(?:[a-zA-Z0-9_]+)?}?)/g) || []
                          ^

TypeError: Cannot read property 'match' of undefined
    at interpolate (project_route\node_modules\dotenv-expand\lib\main.js:9:27)
    at dotenvExpand project_route\node_modules\dotenv-expand\lib\main.js:37:32)
    at project_route\node_modules\dotenv-cli\cli.js:19:3
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (project_route\node_modules\dotenv-cli\cli.js:18:7)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
error Command failed with exit code 1.
```

**ENV_VARIABLE** is being loaded as _undefined_ so envValue = undefined, thus envValue.match throws an error

**Comment by entropitor** [comment]
Hey, can you try if you have the same bug with the latest version of the raw `dotenv` package?

If so, you need to file the bug there, if not, I can look into upgrading the required dotenv  version. Just let me know in that case

I'm gonna close for now. I can reopen if the latest version of dotenv works

**Comment by giuliano-sev** [comment]
`dotenv` package works fine for me running:

```
$ node

$ const env = require('dotenv').config()
undefined

$ env.parsed.ENV_VARIABLE
''
```

It returns empty string instead of undefined. 

Thank you, Jens

**Comment by entropitor** [comment]
Okay, this seems to be a legit issue then. Feel free to upgrade the dotenv version and make a pull request if you want this fixed soon

**Comment by entropitor** [comment]
@giuliano-sev Sorry for the long wait. version 3.0.0 should have its dependencies bumped so give it a go if you are still looking for it
