### ISSUE TITLE
feature: add cross-var support

### ISSUE THREAD

**Issue by ArrayKnight** [entropitor/dotenv-cli#27]
I've just started to use `dotenv-cli` with `cross-var` to be able to use `.env` variables in my package.json. I wrote about it here:
https://medium.com/@arrayknight/how-to-use-env-variables-in-package-json-509b9b663867

I'd like to ask if you think this feature belongs as part of this tool or if I should create something new.

**Comment by entropitor** [comment]
So if understand it correctly, it's about being able to interpret variables immediately without needing a bash script around it?

**Comment by ArrayKnight** [comment]
Yes, in a cross platform way.

**Comment by entropitor** [comment]
@ArrayKnight I'd not necessarily be against doing it in this repo / package but I would potentially only do it if a certain flag is set (depending on how it would work exactly)

And there should be good documentation when run from the shell because I'm guessing many shells will do eager evaluation so `dotenv` will get the empty string because the shell already parsed the env variable before passing it to us. And this will probably trick people up

Does that make sense?

**Comment by ArrayKnight** [comment]
The additional flag part makes sense (`-i` or `--interpretVariables` or `-s` or `--substituteVariables` or `-v` or `--variables` or ?) and then you maintain backwards compatibility.

Documentation is always a good idea.

I think that if the shell already does the substitution before this package can get to it, that's not really an issue since they were likely expecting that. And then if that's not the default behavior of the shell, they have to opt into substitution via the flag, which would also be by intent.

The only case I can think of is if auto substitution occurs and it's for an environment variable that hasn't been loaded yet. I think this is what you're talking about...

This makes me realize I might have not thoroughly tested this situation in my own implementation

**Comment by ArrayKnight** [comment]
Looks like variables need to be wrapped in single quotes to prevent the shell from replacing them before our script can run

**Comment by entropitor** [comment]
>I think that if the shell already does the substitution before this package can get to it, that's not really an issue since they were likely expecting that.

Yes, but many people don't know about this so it's good to add this as a warning to the README ("Make sure your variables aren't parsed by your shell before passing to dotenv"). The `--` trick is also fairly standard practice but nobody seems to know it.

Regarding the name. I don't care so much. `-v` might be confusing / useful for a potential future `verbose` mode so I wouldn't pick that but for the rest, I'm fine with whatever. (In retrospect I'd have probably picked `-f` over `-e` for selecting the file anyway so...)

**Comment by ArrayKnight** [comment]
Turned out the single quote approach had a flaw in certain commands. By switching over to using the Windows approach to variables `%`, we don't have to deal with variables being auto substituted (tested with Git Bash, CMD, and PowerShell) and we don't need a flag turn on variable substitution. Also tested on MacOS with Terminal and ZSH.

**Comment by entropitor** [comment]
Can this be closed then?
