### ISSUE TITLE
Not able to echo env vars

### ISSUE THREAD

**Issue by rbrtmrtn** [entropitor/dotenv-cli#31]
Hello,

First off, thank @entropitor for all of your hard work this awesome tool and I can't wait to start using it!

I've installed `dotenv-cli` as a dev dependency and created a `.env` file in my working directory. This is just a test so far so the `.env` looks like this:

```
FOO=bar
```

I can run `npx dotenv -p FOO` and it prints `bar` as expected. However, if I run `npx dotenv -- echo "$FOO"` it prints an empty line. Am I doing something wrong?

Thank you in advance for any help with this! 🤩

**Comment by entropitor** [comment]
Yes, the problem has to do with how the shell works.

With your command, the shell will interpret this. One of the first things it does is do the interpolation
```
npx dotenv -- echo "$FOO"
```
`$FOO` is replaced by the env variable named `FOO` which is probably unset, so you get the empty string

```
npx dotenv -- echo ""
```

Now `npx` is run which runs `dotenv -- echo ""` which runs `echo ""` (where the last command has access to the env variable `FOO=bar`)

I think `npx dotenv -- bash -c 'echo "$FOO"'` should work as everything between `'` is not interpreted so env variables are not replaced. Now `dotenv-cli` will run `bash -c 'echo "$FOO"'` with the env variable set which means `bash` will run `echo "$FOO"` in the right environment which should print correctly.

**Comment by rbrtmrtn** [comment]
Extremely helpful — thank you for taking the time to explain @entropitor .

**Comment by entropitor** [comment]
@rbrtmrtn No problem. I've been tripped up a lot by early shell interpolation / env variables from the wrong process. It's quite confusing sometimes 😅

**Comment by mikeybinnswebdesign** [comment]
Is there a way to make this work on multiple environments? Bash doesn't work on Windows
