### ISSUE TITLE
Export the variables if no command is given

### ISSUE THREAD

**Issue by RamIdeas** [entropitor/dotenv-cli#36]
Would you be open to exporting the variables for use after running the cli?

My use-case is, In package.json scripts, I would like to reference the variables in the .env file.

Ideally, `dotenv echo $VAR_NAME` would work, but `$VAR_NAME` is evaluated too early so I have to do something like `echo $(dotenv -p $VAR_NAME)` which is very verbose.

I was thinking we could support `dotenv; echo $VAR_NAME` or maybe a new flag if you'd prefer?

**Comment by entropitor** [comment]
@RamIdeas this is simply not possible because it's not dotenv-cli who evaluates too early but your shell before even passing this value to dotenv-cli, see also https://github.com/entropitor/dotenv-cli/issues/31#issuecomment-599196485 for more information

**Comment by RamIdeas** [comment]
I feel like I didn't explain myself clearly enough. I'm await it's the shell that evaluates early.

My recommendation is to export the vars if no command is given. Notice the semicolon in the example on last line?

**Comment by entropitor** [comment]
Ah okay, that makes more sense.

However, I don't think `dotenv` can change the env values of the outer shell script, that seems like it would be dangerous security wise? 

```bash
$ URL=example.com
$ bash -c 'echo $URL' # doesn't output google.com because wasn't exported
$ export URL=example.com
$ bash -c 'echo $URL' # does output goolge.com because it was exported
$ bash -c 'export URL=google.com'
$ echo $URL      # doesn't have google.com because child doesn't export to parent
```

I'd be happy to implement something if you can prove me wrong. I'd probably put it behind a feature flag then but for the rest it should be fine. I'm just not sure if it can be done.
