### ISSUE TITLE
Support .env, .env.local, .env.<environment> practice

### ISSUE THREAD

**Issue by plashenkov** [entropitor/dotenv-cli#37]
Hey!

Thanks for this awesome lib!

It would be nice if `dotenv-cli` could read variables from multiple `.env` files. There is a common approach to use `.env` and `.env.local`, and maybe `.env.<environment>` (`.env.production`, `.env.development`, etc.) schema.

Here are the examples:
- https://symfony.com/doc/current/configuration.html#overriding-environment-values-via-env-local (Symfony)
- https://nextjs.org/docs/basic-features/environment-variables#default-environment-variables (Next.js)
- https://create-react-app.dev/docs/adding-custom-environment-variables/#what-other-env-files-can-be-used (Create React App)

It's a common and nice practice since you can use common defaults in an `.env` file and then override them in a machine-specific `.env.local`. Usually you commit `.env` to a git repository and do not commit `.env.local` (secrets go there).

Currently we can use `-e envfile` many times, but it would be nice to have, for example, a special argument to activate this schema:

```bash
dotenv --cascade -- <command with arguments>
# or different argument name of course
```

**Comment by entropitor** [comment]
@plashenkov so basically you would want a flag like `--cascade` or `--local` that is basically equivalent to `-e .env -e .env.local`? Or how would it work exactly?

**Comment by plashenkov** [comment]
Yep, usually these files participate in this flow:

`.env.<environment>.local`, `.env.<environment>`, `.env.local`, `.env`

Files on the left have more priority than files on the right. I.e. if `.env.local` and `.env` have the same variable, the value from `.env.local` has to be taken.

And _real_ environment variables always win over env vars created by any of the .env files:

```bash
SOMEVAR=somevalue dotenv --cascade -- <command with arguments>
```
SOMEVAR=somevalue should take the top precedence.

**Comment by plashenkov** [comment]
`.env.<environment>.local`, `.env.<environment>`, `.env.local`, `.env`

Where <environment> = 'production', 'development', 'test', i.e. NODE_ENV

**Comment by entropitor** [comment]
@plashenkov the problem is that we should probably not read out `NODE_ENV` as there is also `RAILS_ENV` etc. and that would explode quickly (and what if both `NODE_ENV` and `RAILS_ENV` are defined...)

What could work is something like `--cascade` which defaults to development and then `--cascade=production` to change the environment. WDYT?

**Comment by plashenkov** [comment]
I think that's great. Probably we shouldn't use 'development' by default since sometimes 'dev' can be used (in Symfony for example). Maybe if omitted we should just ignore `.env.<environment>` and `.env.<environment>.local` files.

**Comment by entropitor** [comment]
@plashenkov That makes sense! You want to take a stab at it?

**Comment by plashenkov** [comment]
Sorry I'm not so fluent in English. :) What does "want to take a stab at it" mean?

**Comment by entropitor** [comment]
Ah sorry, I meant to ask if you want to try implementing this feature and make a pull request?

**Comment by plashenkov** [comment]
Yep, I think I'll try. Nearest days.

**Comment by plashenkov** [comment]
Ok, done. Is it okay for you to update the help text and readme?

**Comment by plashenkov** [comment]
Is it okay to use -c instead of --cascade?

**Comment by rebasecase** [comment]
Sorry to necro this.

I found the documentation really difficult to follow What does `-c` do? `-c blah` does that load `.env.blah` and `.env.blah.local` (no it doesn't seem to)

also

```
Multiple .env files can be specified, and will be processed in order:

$ dotenv -e .env3 -e .env4 -- <command with arguments>
```

Implies .env4 overwrites .env3, which it does not?

```
> cat .env.foo
MY_VAR=1
> cat .env.bar
MY_VAR=2
> npx -y dotenv-cli -e .env.foo -e .env.bar -- sh -c 'echo $MY_VAR'
1
```

```
> cat .env.bar.local
MY_VAR=BAR_LOCAL
> npx -y dotenv-cli -e .env.bar -- sh -c 'echo $MY_VAR'
2
```

**Comment by entropitor** [comment]
How would you rewrite this paragraph from the README then?

> Some applications load from .env, .env.development, .env.local, and .env.development.local (see https://github.com/entropitor/dotenv-cli/issues/37 for more information). dotenv-cli supports this using the -c flag for just .env and .env.local and -c development for the ones above

With regards to the order, that is because defined env variables will not be overwritten, so you can easily overwrite it from the command line. I'm happy to accept a PR to explain this more clearly as well 👍

**Comment by rebasecase** [comment]
```dotenv-cli loads files **in order**, but only sets variables if they **haven’t already been set**.```

```
Some applications load environment variables from multiple `.env` files depending on the environment:

- `.env`
- `.env.local`
- `.env.development`
- `.env.development.local`

`dotenv-cli` supports this using the `-c` flag:

- `-c` loads `.env` and `.env.local`
- `-c test` loads `.env`, `.env.local`, `.env.test`, and `.env.test.local`

See [issue #37](https://github.com/dotenv-org/cli/issues/37) for more details.
```

**Comment by entropitor** [comment]
Sorry for the troubles! I've updated the README.md
