### ISSUE TITLE
variable expansion in command

### ISSUE THREAD

**Issue by aymericbouzy** [entropitor/dotenv-cli#41]
I was trying to do this:

```sh
dotenv echo $HELLO
```

with `.env` file looking like:

```
HELLO=world
```

and was expecting to get `world` as a result, but this doesn't work obviously, since $HELLO gets expanded too early.

I was hoping the documentation would give me a hint into how to tweak my command to get the desired result? I'm not that good at bash.

I can make a PR to the documentation when I find how to make it work if you believe other people could find themselves in the same situation.

**Comment by entropitor** [comment]
https://github.com/entropitor/dotenv-cli/issues/31#issuecomment-599196485

Feel free to make a PR to update the README
