### ISSUE TITLE
.env.<environment> with the -e flag

### ISSUE THREAD

**Issue by davecardwell** [entropitor/dotenv-cli#43]
I was surprised to find that passing the `-c` and `-e` flags together didn’t cause dotenv-cli to check for environment-specific versions of my indicated `.env` file.

eg.,
```sh
dotenv -c production -e ../www/.env …
```

I was expecting that to expand to `../www/.env.local`, `../www/.env.production.local`, `../www/.env.production`, `../www.env`.

I see from the code that this cascading is only performed for the `.env` file in the same directory. Would there be any interest in giving any `-e` files the same treatment, either by default or with an extra command line flag?

**Comment by entropitor** [comment]
I'm open to that. It would probably require a bit of a refactor though but for the rest 👍 

I don't have capacity to implement it myself, but I can review a Pull Request :)

**Comment by davecardwell** [comment]
Thanks! I had a crack at it in #44
