### ISSUE TITLE
Register additional bin called `dotenv-cli`

### ISSUE THREAD

**Issue by sprilukin** [entropitor/dotenv-cli#45]
Currently library registers only a single binary called `dotenv`.

I'm using this library in the following manner:

1. i installed it locally: `npm install dotenv-cli --save-dev (i can not install it globally since it's executed on the CI and i have no acces to CI server)
2. in the npm scripts i have the following entry:
```
scripts: {
      test: "dotenv -c -- node scripts/my-script"
}
```

the problem is that there is another global command dotenv registered in the system.
In my case this is [ruby-gem `dotenv`](https://rubygems.org/gems/dotenv/versions/2.1.1)

So this npm script uses globally installed ruby `dotenv` command rather than local `dotenv` from `dotenv-cli` package

**Solution**: dotenv-cli library can register additional bin script, for example `dotenv-cli` so i can rewrite my script:
```
scripts: {
      test: "dotenv-cli -c -- node scripts/my-script"
}
```

**workaround**:
use `./node_modules/.bin/dotenv` rather than `dotenv`

**Comment by entropitor** [comment]
I get where you are coming from but what if people have a `dotenv-cli` installed globally from someplace else? Then they would still run into this issue, no?

(Btw I think you can also replace it with `npx dotenv`)

I'm not entirely against this change but I'm just a bit sceptical it's something this library needs to solve.

**Comment by sprilukin** [comment]
This was my local issue.
In fact npm update PATH env variable with `./node_modules/.bin` something like `PATH=./node_modules/.bin:$PATH`, 
so local version always takes priority over global command 
Issue could be closed, sorry for disturbing

**Comment by rickysullivan** [comment]
@entropitor Did you mean `npx dotenv-cli`?

**Comment by entropitor** [comment]
yes
