### ISSUE TITLE
LANG not successfully loaded from `.env` files

### ISSUE THREAD

**Issue by basarat** [entropitor/dotenv-cli#47]
# Repro
Have the following files: 

`.env`: 
```
LANG=en-US
GENERAL=works
```

`hello.js`: 
```
console.log('LANG', process.env.LANG);
console.log('GENERAL', process.env.GENERAL);
```

And run 

```
node_modules/.bin/dotenv node hello.js
```

# Expected result 

```
LANG en-US
GENERAL works
```

# Actual result 

```
LANG en_AU.UTF-8
GENERAL works
```

Notice that `LANG` was not loaded correctly. 

# More 

I've narrowed it down to the call to `dotenvExpand` here : https://github.com/entropitor/dotenv-cli/blob/88badb1a0a63e5ddc3225556a24bc386dc2fde58/cli.js#L54 

If I log the following: 

```
// your code
paths.forEach(function (env) {
  dotenvExpand(dotenv.config({ path: path.resolve(env) }))
})

// my log statements
console.log('FROM loaded', dotenv.config({ path: path.resolve('.env') }));
console.log('FROM expanded', dotenvExpand(dotenv.config({ path: path.resolve('.env') })));
console.log('VALUES:', 'LANG',  process.env.LANG, 'GENERAL', process.env.GENERAL);
```

I get (notice how `LANG` is changed in `expanded`) : 
```
FROM loaded { parsed: { LANG: 'en-US', GENERAL: 'works' } }
FROM expanded { parsed: { LANG: 'en_AU.UTF-8', GENERAL: 'works' } }
VALUES: LANG en_AU.UTF-8 GENERAL works
```

**Comment by entropitor** [comment]
I think it's because LANG is set before you call dotenv and dotenv will not overwrite env variables you have already set so you can easily override them from the command line. I'm open to a PR that adds a flag that avoids that behaviour

**Comment by entropitor** [comment]
I'm gonna close this as this sounds more like a feature request and I want to keep this to a clean inbox. Feel free to send over a Pull Request if you want to add it yourself.
