### ISSUE TITLE
`CHANGELOG` missing

### ISSUE THREAD

**Issue by MichaelDeBoey** [entropitor/dotenv-cli#48]
I just saw the package is updated to `v4.0.0`, but I can't find any CHANGELOG to check out the changes.

Would you be so kind to provide us with a decent CHANGELOG please? 🙂

Thanks for all your hard work @entropitor! 🙂

**Comment by entropitor** [comment]
I try my best to add some stuff in the releases. For the v4.0.0 release I forgot but I updated it now: https://github.com/entropitor/dotenv-cli/releases/tag/v4.0.0. I hope that's enough for you

**Comment by MichaelDeBoey** [comment]
Thanks @entropitor! 👊
