### ISSUE TITLE
dotenv-cli not gracefully exiting completely when used with docker 

### ISSUE THREAD

**Issue by MengRS** [entropitor/dotenv-cli#49]
I have the following script in my `package.json`:
`"start:docker": "dotenv -- docker compose -f docker/docker-compose.yml up"`

When I exit out of this process - I type `ctrl`+`c` and it partially exits out but doesn't completely exit out.  How can I get it to completely exit out when I type `ctrl`+`c`?

`actual behaviour` (hangs -> have to hit `ctrl` + `c` AGAIN for it to fully exit):
![image](https://user-images.githubusercontent.com/7980628/116140002-89f2fc80-a68b-11eb-9b14-04fd9902bfc8.png)

`expected behaviour` (doesn't hang -> do NOT have to hit `ctrl` + `c` AGAIN for it to fully exit):
![image](https://user-images.githubusercontent.com/7980628/116139846-56b06d80-a68b-11eb-9c52-31a0a27ae786.png)

I have some scripts I am chaining with this one so it presents an issue (note when I don't use `dotenv`, I do not experience the above issue)

**Comment by entropitor** [comment]
Does the problem also happen when you don't use yarn? As I think this could actually be because of yarn scripts instead of `dotenv-cli`. 

In case of docker-compose, you should actually be able to use pass `--env-file` instead of using dotenv-cli

**Comment by MengRS** [comment]
> Does the problem also happen when you don't use yarn? As I think this could actually be because of yarn scripts instead of `dotenv-cli`.
> 
> In case of docker-compose, you should actually be able to use pass `--env-file` instead of using dotenv-cli

I use `npm` (not `yarn`) - I'm on npm version 7.11.1 (latest one as of right now)...  

I tried running the following command in the terminal (that yielded the same results): `npx dotenv -- docker compose -f docker/docker-compose.yml up`  <-- other than that, is there a way I can run the `dotenv-cli` without using `npm`?

**Comment by MengRS** [comment]
Going to close the issue, although I haven't found root cause - I think this issue has to do with my terminal rather than `dotenv-cli` (with a bare bones `.zshrc` file - I got desirable results for _some_ npm scripts)

**Comment by entropitor** [comment]
> other than that, is there a way I can run the dotenv-cli without using npm?

`./node_modules/.bin/dotenv` should do the trick as well (or installing globally and then running `dotenv`
