### ISSUE TITLE
Command Substitution does not work

### ISSUE THREAD

**Issue by RohitRox** [entropitor/dotenv-cli#54]
Sample .env file that uses Command Substitution:
https://github.com/bkeepers/dotenv#command-substitution
```
postgresql://$(whoami):@localhost:5432/my_db?schema=public
```
`$(whoami)` is not resolved

**Comment by entropitor** [comment]
Sounds like a feature request for https://github.com/motdotla/dotenv which does the actual dotenv parsing. Feel free to file an issue there or create an extension like https://github.com/motdotla/dotenv-expand. After something like that exists, it should be an easy fix.
