### ISSUE TITLE
Is processing commands arguments as its own

### ISSUE THREAD

**Issue by kswope** [entropitor/dotenv-cli#58]
This works
```
npx dotenv -e env ava -w
```

This doesn't
```
npx dotenv ava -v

/backend/node_modules/dotenv-cli/cli.js:62
    variables.push(...argv.v.map(validateCmdVariable))
                             ^

TypeError: argv.v.map is not a function
    at Object.<anonymous> (/Users/kevin/Development/JavaScript/scrolli/backend/node_modules/dotenv-cli/cli.js:62:30)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47





```

**Comment by entropitor** [comment]
please read the readme before filing isues https://github.com/entropitor/dotenv-cli#flags-to-the-underlying-command

**Comment by kswope** [comment]
I saw that but I think I got confused because the example is backwards

This is what is there now:

E.g. the following command without dotenv-cli:
$ mvn exec:java -Dexec.args="-g -f"
will become the following command with dotenv-cli:
$ dotenv -- mvn exec:java -Dexec.args="-g -f"

It should be written:

$ dotenv -- mvn exec:java -Dexec.args="-g -f"
will become the command to dotenv-cli
$ mvn exec:java -Dexec.args="-g -f"


Also: this way of parsing command line arguments unfortunately doesn't work well with npm scripts, like dotenv and godotenv do.


in package.json
"test": "node -r dotenv/config node_modules/.bin/ava",
$ npm run test -- -wv
runs
node -r dotenv/config node_modules/.bin/ava "-wv"

in package.json
"testwithgodotenv": "godotenv ava",
npm run testwithgodotenv -- -wv
runs
godotenv ava "-wv"

in package.json
"testwithdotenv": "dotenv ava",
$ npm run testwithdotenv -- -wv
runs
dotenv ava "-wv" <--- the original error in the issue

**Comment by entropitor** [comment]
1. The readme says how to construct the dotenv command. I think this is what is most useful to people getting started. Feel free to create a PR to improve it but keep in mind that it should explain how to use it, not how it works
2. Given it's such a common idiom to ignore everything after `--`, `npm` and others also use it so what you want is 
```
npm run testwithdotenv -- -- -wv
```
Notice the double `--`, one to say, `npm` don't parse anything after these but pass them along and another to say to `dotenv-cli` do not parse anything after these...

So dotenv sees `dotenv ava -- "-wv"` and ava sees `ava "-wv"`
