### ISSUE TITLE
Upgrade dotenv version?

### ISSUE THREAD

**Issue by karlhorky** [entropitor/dotenv-cli#64]
Hi there, thanks for `dotenv-cli`! 

The `dotenv` version in `dependencies` is pretty old - `^8.1.0`, and the latest version is `16.0.0`. Would you be open to upgrading this?

**Comment by entropitor** [comment]
Yes, sure, I guess we should just make it a breaking change then?

**Comment by karlhorky** [comment]
Yep, seems like that would be good, with all of the breaking changes that `dotenv` introduced! 👍

**Comment by karlhorky** [comment]
If you're doing a new major version, an alternative to upgrading `dotenv` all the time would be to move `dotenv` to `peerDependencies` and accept any version above `8.1.0`, which would allow consuming projects to choose their version.

**Comment by entropitor** [comment]
@karlhorky Yes but that wouldn't work for a global install right? Which I think is a genuine use case of dotenv-cli.

**Comment by entropitor** [comment]
https://github.com/entropitor/dotenv-cli/releases/tag/v5.0.0

**Comment by karlhorky** [comment]
> Yes but that wouldn't work for a global install right? Which I think is a genuine use case of dotenv-cli.

Yeah I guess that may be a problem in that case. Thanks for the release!
