### ISSUE TITLE
Setting variable does not work when value has dash

### ISSUE THREAD

**Issue by rpmansion** [entropitor/dotenv-cli#65]
For instance, setting `dotenv -v AWS_REGION=eu-west-1` gives you an error of `Unexpected argument AWS_REGION=eu-west-1. Expected variable in format variable=value`

**Comment by hendriku** [comment]
Using dotenv-cli v3.2.0 seems to fix this issue.

**Comment by hendriku** [comment]
Another workaround is intercepting the dotenv cli command with [cross-env](https://www.npmjs.com/package/cross-env) to manually pass additional command line arguments
e.g.

`dotenv -- cross-env NODE_OPTIONS='--inspect' next dev`

**Comment by entropitor** [comment]
We can improve this regex https://github.com/entropitor/dotenv-cli/blob/master/cli.js#L50

This is because of this security issue: https://github.com/entropitor/dotenv-cli/pull/57#issuecomment-951203381

Feel free to create a PR to fix this

**Comment by MorisR** [comment]
I think the same bug applies here:

### Input:
![image](https://user-images.githubusercontent.com/10247681/158856893-cd579c25-7f24-42f8-83dc-284c612c54ac.png)

### Output:
![image](https://user-images.githubusercontent.com/10247681/158857001-5b7257d1-aa03-4fed-b7ba-8e9579fca1e2.png)

**Comment by entropitor** [comment]
You're just seeing the default value because you haven't set PUBLICPATH.
That's how it's supposed to work I think

**Comment by MorisR** [comment]
yeah but ```}``` shouldn't be part of the default value :/

![image](https://user-images.githubusercontent.com/10247681/158859313-617f0119-a229-412b-91d9-ed9db322b627.png)
that's from https://www.npmjs.com/package/dotenv-expand

**Comment by entropitor** [comment]
That's probably in dotenv-expand. This package is just a simple wrapper around that one...

**Comment by MorisR** [comment]
https://github.com/motdotla/dotenv-expand/issues/70
yeah... it's a bug there, thanks.

**Comment by AndrewAllison** [comment]
Had a crack at a PR https://github.com/entropitor/dotenv-cli/pull/69
