### ISSUE TITLE
dontenv-cli not escaping dollar sign correctly

### ISSUE THREAD

**Issue by emmett-neighborschools** [entropitor/dotenv-cli#66]
#### Environment
"dotenv-cli": "^5.0.0" (installed as dev dependency, not globally)
Mac OSX 11.1

I'm finding that this tool is incorrectly escaping the `$` character when it's referencing a variable in a file that has been run with `source`.

#### Steps to Reproduce
Create a new file `~/.envTest` file with the following:
```bash
export TEST_VAR="default\$default"
```

Run 
```
$ npx dotenv -e ~/.envTest -- printenv TEST_VAR
default$default
$ source ~/.envTest
$ npx dotenv -e ~/.envTest -- printenv TEST_VAR
default
$ printenv TEST_VAR
default$default
```

This issue is forcing me to use a separate environment variable file that I don't `source` in order to allow this to work for my use case that requires the dotenv cli.

**Comment by entropitor** [comment]
This is probably a bug in `dotenv` itself or in `dotenv-expand`
