### ISSUE TITLE
Fail to load env

### ISSUE THREAD

**Issue by winston0410** [entropitor/dotenv-cli#77]
base ❯ npx dotenv-cli -v FOO=bar -- echo $FOO   

Which I am expecting to see bar there

**Comment by entropitor** [comment]
https://github.com/entropitor/dotenv-cli/issues/31#issuecomment-599196485

**Comment by simonpai** [comment]
Hi @entropitor,
I'm following your comment on #31 on macOS and still got empty result:

```
npx dotenv -v FOO=bar -p FOO
-> bar
npx dotenv -v FOO=bar -- bash -c 'echo $FOO'
-> (nothing)
```

Do you have any idea what could go wrong here? Thanks.

**Comment by entropitor** [comment]
<img width="525" alt="image" src="https://user-images.githubusercontent.com/896093/187378514-0e134e81-81ab-461d-ba53-14062f870e6f.png">
Seems to work for me 🤷 I guess something is pre-evaluating the $FOO... Are you putting this in npm scripts? Because that might be the issue.

**Comment by simonpai** [comment]
<img width="587" alt="Screen Shot 2022-08-30 at 4 13 09 PM" src="https://user-images.githubusercontent.com/785058/187385736-24883b8e-48b3-4c0b-b602-d2c18a9bc45c.png">

Strange, I believe I was doing exactly the same thing... or maybe my bash is problematic. Anyway, thanks for your quick response. I guess I'll try to work around in some other way and share what I find if any. Don't want to waste your time on this.
