### ISSUE TITLE
Change load order of multiple .env files

### ISSUE THREAD

**Issue by hyoretsu** [entropitor/dotenv-cli#81]
I have a production database that I don't want going to GitHub in `.env.local` and a development generic database credential in `.env.development`. But since the order puts `.env.local` after `.env.development`, that doesn't work.

Suggested load order:
`.env` > `.env.local` > `.env.development` > `.env.development.local`

**Comment by entropitor** [comment]
Can you just not call it .env.producrion.local?

**Comment by hyoretsu** [comment]
It's not production, it's development. And I want to upload that string to GitHub. My "change", after searching the commits, is what's originally done before [6b1d121](https://github.com/entropitor/dotenv-cli/commit/6b1d121086b82b4066d33516a67b708673338dc5).

**Comment by hyoretsu** [comment]
After checking Next.js load order, I concede. But you should note in Docs that any environment file prefix other than "development" is also allowed.
