### ISSUE TITLE
Override system variables

### ISSUE THREAD

**Issue by llovett2** [entropitor/dotenv-cli#85]
Resurrecting #46, it would be great to have an option to ignore environment vars and set the variables from a file. According to the last comment in that issue, the override feature is now available in dotenv. Ideally a `-o`/`--override` flag would enable this functionality.

**Comment by entropitor** [comment]
Feel free to make a PR

**Comment by jfairley** [comment]
I have a PR for this at https://github.com/entropitor/dotenv-cli/pull/87.
